# Generated by Django 5.2.4 on 2025-08-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0003_userimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='predicted_disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
