# Generated by Django 5.2.4 on 2025-08-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0004_userimage_predicted_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='predicted_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
