# Generated by Django 5.2.4 on 2025-08-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin_app', '0005_userimage_predicted_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='cure',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='prevention',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='remedies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userimage',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
