from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
import io
from datetime import datetime

def generate_pdf_report(user_name, disease_name, symptoms, prevention, remedies, cure, image_path):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = styles['Title']
    elements.append(Paragraph("🩺 Skin Disease Detection Report", title_style))
    elements.append(Spacer(1, 16))

    # User Info
    info_data = [
        ["Patient Name:", user_name],
        ["Report Date:", datetime.now().strftime("%d-%m-%Y %H:%M")],
        ["Disease Predicted:", disease_name]
    ]
    table = Table(info_data, colWidths=[120, 350])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.lightgrey),
        ('TEXTCOLOR', (0,0), (0,-1), colors.black),
        ('ALIGN', (0,0), (-1,-1), 'LEFT'),
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 16))

    # Disease Image
    if image_path:
        try:
            img = RLImage(image_path, width=3*inch, height=3*inch)
            img.hAlign = 'CENTER'
            elements.append(img)
            elements.append(Spacer(1, 16))
        except Exception as e:
            elements.append(Paragraph(f"[Image Error: {e}]", styles['Normal']))

    # Disease Sections
    def add_section(title, content):
        if content:
            elements.append(Paragraph(f"<b>{title}:</b>", styles['Heading3']))
            elements.append(Paragraph(content, styles['Normal']))
            elements.append(Spacer(1, 12))

    add_section("Symptoms", symptoms)
    add_section("Prevention", prevention)
    add_section("Remedies", remedies)
    add_section("Cure", cure)

    # Disclaimer
    disclaimer = "⚠️ This report is generated by an AI system. Please consult a dermatologist for professional advice."
    elements.append(Paragraph(disclaimer, ParagraphStyle('Disclaimer', textColor=colors.red, fontSize=9, italic=True)))

    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer
